### PR TITLE
Fix strange loading bug on Paper

### PR DESCRIPTION
**Pull request by mbax**
I had some trouble getting the plugin to load, so I went looking and found this unusual code issue! Fixed it up and it runs good as new!

I hope this PR helps your plugin run on more software! 😊

- mbax

### CODE REVIEW

**Review by NickAcPT — APPROVED** [review]
LGTM

**Review by Chew — APPROVED** [review]
Tested myself, works fine!

**Review by Draycia — APPROVED** [review]
LGTM

**Review by Turbotailz — APPROVED** [review]
Fantastic work as always Mr Baxter

**Review by egg82 — APPROVED** [review]
Looks good! Should be able to run on more software now, allowing more users to be able to make use of the plugin's functionality.

**Pull request closed without merging**
