### PR TITLE
add ProtectNamedMobs flag

### PR DESCRIPTION
**Pull request by akdukaan**
Players on my server make mob farms and claim them. Some of these farms require hostile mobs (endermites in an enderman farm or zombies in a villager farm). Even though the land is claimed, other players are able to kill the endermite. GP does not include a way to protect against this. With the addition of a NamedMobInvulnerability flag, players can finally protect against this type of grief.

### CODE REVIEW

**Comment by ShaneBeee** [comment]
Do you think it might be a good idea, to add a check for claim owner/members?
In my opinion, if I own said claim I should be allowed to kill these mobs if at some point I want to/need to get rid of them.

**Comment by akdukaan** [comment]
Yep. I think that containertrust makes most sense for this because containertrust is also what's needed to attack passive mobs. I also renamed the flag to ProtectNamedMobs because that seems more accurate with these new changes, and it's more coherant.

**Review by ShaneBeee — APPROVED** [review]
Looks good to me 👍

**Comment by ShaneBeee** [comment]
Thank you for your contribution

**Pull request merged**
